version: '3.8'

services:
  downloader:
    build:
      context: .
      target: downloader
    volumes:
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python downloader.py